// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function ReactVersionOfDomWithRef(Props) {
  var inputRef = React.useRef(null);
  return React.createElement(React.Fragment, undefined, React.createElement("button", {
                  onClick: (function (_event) {
                      var ref = inputRef.current;
                      if (ref == null) {
                        return ;
                      }
                      var setValue = (function(domNode, value) {domNode.value = value;});
                      return setValue(ref, "Hmm...");
                    })
                }, "Inner Text"), React.createElement("input", {
                  ref: inputRef,
                  type: "text"
                }));
}

var make = ReactVersionOfDomWithRef;

export {
  make ,
  
}
/* react Not a pure module */
